---

- name: "FIX: Ubuntu 16.04 LTS doesn't come with certain modules, required by ansible"
  raw: apt-get install python-minimal aptitude -y
  become: true
  become_user: root
  become_method: sudo

- name: Upgrade apt packages
  apt: upgrade=yes
       update_cache=yes

- name: Install NTP
  apt: pkg=ntp
  tags: common
