# defaults file for mongodb install

# Add an apt key by id from a keyserver
- name: Add PGP key
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=EA312927
  tags: mongodb

- name: add mongodb repository
  apt_repository: "repo='deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse' state=present update_cache=yes"
  tags: mongodb

- name: install mongodb
  apt: "pkg=mongodb-org"
  tags: mongodb

- name: create the service
  template: src=mongodb.service.j2 dest=/etc/systemd/system/mongodb.service
  tags: mongodb

- name: run the service
  service:
    name: mongodb
    state: started
  tags: mongodb