system_packages:
  - python-setuptools
  - python-dev
  - python-pip
  - libncurses-dev
  - git
  - make
  - gcc
  - gfortran
other_python_pkgs:
  - build-essential
  - libreadline-gplv2-dev
  - libncursesw5-dev
  - libssl-dev
  - libsqlite3-dev
  - tk-dev
  - libgdbm-dev
  - libc6-dev
  - libbz2-dev
  - libblas-dev
  - liblapack-dev
  - libatlas-base-dev
  - python-passlib
